# Pauta Auxiliar 0: Recuerdo de Python y Google Colab

**Auxiliares: Daniela Espinoza, Cristián Llull Torres, Benjamín Osses,
Anish Samtani y Marcelo Zamorano<br>
Profesores: Nelson Baloian, Iván Sipirán, Patricio Poblete<br>
Curso: CC3001 Algoritmos y Estructuras de Datos**




## Introducción a Google Colab

Google Colab o "Colaboratory" es un entorno virtual para ejecutar Notebooks de Python. Este entorno es muy sencillo de utilizar y permite el acceso a GPU adicional a la del computador de manera gratuita, además de se pueden compartir archivos de manera muy sencilla.

A continuación veremos algunos de los atributos básicos de los *notebooks* de Python.
### Celdas de texto

En un notebook de Python existen esencialmente dos tipos de celda: las de código y las de texto (Markdown). Esta es una celda de texto y existen múltiples cosas que se pueden hacer en ellas.

* Se pueden colocar títulos, subtítulos, subsubtítulos, etc. Para conseguirlo basta con agregar símbolos "#" al inicio de la frase (ver este bloque de texto). Estos títulos y sus subsecuentes subtítulos (hasta seis "#") se pueden anidar y crear un índice, que se puede revisar al costado izquierdo, haciendo click en el símbolo de tres líneas arriba de la lupa.

* Se puede escribir texto normal, *en cursiva*, **en negrita** o en formato `código`.

* También se puede escribir en $\LaTeX$, ya sea dentro de una misma línea $f(x) = 3^x$, como también ecuaciones centradas:

$$
\sum_{i=1}^{n} i^2 = \frac{n(n+1)(2n+1)}{6}
$$

* También se pueden crear listados como este, donde están las indicaciones para crear notebooks y compartirlos:

  1. Para crear un notebook nuevo: *Archivo>Nuevo Cuaderno*

  2. Para guardar una copia de otro notebook en su cuenta de Google Drive/Github:  *Archivo>Guardar una copia en Drive/Github*

  3. Para compartir el notebook:
    - Ir a *Compartir*
    - En la sección que dice *Acceso general* cambiar a *Cualquier persona con el enlace*
    - Luego seleccionar el tipo de permiso o rol (Lector, Comentador, Editor)
    - Finalmente hacer click en *Copiar enlace*

  4. Para descargar un notebook en formato `.ipynb` (*Interactive Python Notebook*): *Archivo>Descargar>Descargar .ipynb*

  > **Nota**: Cuando entreguen sus ejercicios o tareas, DEBEN entregar el descargable en formato `.ipynb`.

### Celdas de código



## Problema 2

#### El objetivo de esta pregunta es familiarizarnos con la estructura de datos Numpy la cual utilizaremos en remplazo a las listas de Python. A diferencia de estas últimas, Numpy permite controlar el uso de memoria y los recorridos a través de esta de manera eficiente.

In [1]:
import numpy as np

#### a) Crear un arreglo de enteros tamaño 10 que solo contenga ceros.

In [3]:
arreglo = np.zeros(10)
print(arreglo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### b) Itere por el arreglo escribiendo los números del 0 al 9.

In [5]:
for i in range(0,len(arreglo)):
    arreglo[i] = i

print(arreglo)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### c) Multiplique cada uno de los elementos del arreglo por 3.

In [6]:
arreglo = arreglo * 3                                                           # Tambien arreglo *= 3
print(arreglo)

[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]


#### d) En el arreglo, reemplace los números pares por 0 y los impares por 1.

In [8]:
for i in range(0,len(arreglo)):
    if arreglo[i]%2 == 0:
        arreglo[i] = 0
    else:
        arreglo[i] = 1

print(arreglo)

[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]


#### e) Cree una matriz de 3x3 que solo contenga la letra 'a' e imprima la matriz.

In [ ]:
matriz = np.full((3,3), 'a', dtype=object)
matriz[1,2] = 'b'
print(matriz)

[['a' 'a' 'a']
 ['a' 'a' 'b']
 ['a' 'a' 'a']]


#### **Propuesto:** Modifique la matriz de forma que la primera fila de esta tenga solo el caracter 'a', la segunda fila tenga 'aa' y la tercera 'aaa'

In [49]:
for r in range(0,matriz.shape[0]):
    for c in range(0,matriz.shape[1]):
        matriz[r, c] = "a" * (r + 1)

print(matriz)

[['a' 'a' 'a']
 ['a' 'a' 'a']
 ['a' 'a' 'a']]


##Problema 3

Dado un entero n, retorne las primeras n filas del Triángulo de Pascal. En el Triángulo de Pascal, cada número es la suma de los dos números que tiene por encima.

[1]
[1 1]
[1 2 1]
[1 3 3 1]
[1 4 6 4 1]
[ 1  5 10 10  5  1]
[ 1  6 15 20 15  6  1]
[ 1  7 21 35 35 21  7  1]


##Problema 4

El objetivo de esta pregunta es recordar cómo implementar y usar clases en Python. Para esto, modelaremos una batalla pokémon por medio de la creación de una clase Pokémon y Entrenador con los siguientes atributos y métodos.

a) Cree las siguientes clases y funciones.
